set nocompatible              " be iMproved, required
filetype off                  " required

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

Plug 'pseewald/vim-anyfold'
Plug 'fatih/vim-go'
Plug 'github/copilot.vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
"set foldmethod=syntax
set foldlevel=99 " Open all folds
set nocompatible
syntax on
filetype plugin indent on
let g:go_fmt_command = "goimports"
" https://stackoverflow.com/questions/4760428/how-can-i-make-vims-j-and-gq-commands-use-one-space-after-a-period
set nojoinspaces

"call deoplete#custom#option('omni_patterns', { 'go': '[^. *\t]\.\w*' })

" maps shift-tab to next window
nnoremap <S-Tab> <C-W>w

