set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

set foldmethod=syntax
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'pseewald/vim-anyfold'

set nocompatible
syntax on
filetype plugin indent on
let g:go_fmt_command = "goimports"
" https://stackoverflow.com/questions/4760428/how-can-i-make-vims-j-and-gq-commands-use-one-space-after-a-period
set nojoinspaces
